// Auto-generated by LSDE Blueprint Export — Types
using System;
using System.Collections.Generic;

/*
 * LSDE Blueprint Export — Quick Integration Guide
 *
 * Data Flow: BlueprintExport → Scene[] → Block[] + Connection[]
 *
 * Getting Started:
 * 1. Parse the export file into the BlueprintExport root structure
 * 2. For each scene, use entryBlockId to find the start block
 * 3. Execute the block based on its type:
 *    - DIALOG: Display text, resolve characters and emotions
 *    - CHOICE: Present options, filter by visibilityConditions
 *    - CONDITION: Evaluate condition groups in order — single group: true/false ports, multiple groups: case_0..N/default ports. With enableDispatcher: all matching groups fire async tracks, false/default is main continuation
 *    - ACTION: Execute actions using signatures to resolve actionId
 *    - NOTE: Skip (designer-only, not for runtime)
 * 4. Follow connections to the next block(s):
 *    - Match connection.fromId === currentBlock.uuid
 *    - For CHOICE: match connection.fromPort === selectedChoice.uuid
 *    - For CONDITION: single group → fromPort "true"/"false"; switch mode → fromPort "case_0".."case_N" or "default"
 * 5. Use dictionaries to resolve condition keys and action params
 * 6. Use signatures to understand action types and param definitions
 * 7. Repeat until no outgoing connections remain
 */

/// <summary>
/// Reference types exported from the LSDE project configuration.
/// These provide type-safe access to project-defined characters, dictionaries, and action signatures.
/// Map these to your engine&apos;s own types for compile-time validation.
/// </summary>
/// <summary>Characters defined in the project</summary>
public static class lsdeCharacter
{
    public const string l1 = "l1";
    public const string l2 = "l2";
    public const string l3 = "l3";
    public const string l4 = "l4";
    public const string boss = "boss";
}

/// <summary>Dictionary: inventory (1 values)</summary>
public static class lsdeDictionaryinventory
{
    public const string carrot = "carrot";
}

/// <summary>Dictionary: party (3 values)</summary>
public static class lsdeDictionaryparty
{
    public const string l1 = "l1";
    public const string l2 = "l2";
    public const string l3 = "l3";
}

/// <summary>Action signature IDs</summary>
public static class lsdeActionId
{
    public const string moveCameraToLabel = "moveCameraToLabel";
    public const string shakeCamera = "shakeCamera";
    public const string moveCharacterAt = "moveCharacterAt";
}
