// Auto-generated by LSDE Blueprint Export — Enums

/// <summary>
/// Scene identifiers for type-safe access to blueprint scenes.
/// Use these constants to start or reference a specific dialogue sequence.
/// Each value maps to the scene&apos;s UUID — stable even if the scene is renamed.
/// </summary>
public static class LSDE_SCENES
{
    /// <summary>
    /// <para>Scene: simple-dialog-flow</para>
    /// <para>8 DIALOG</para>
    /// <para>Entry: <c>rabbit_rumor-AI</c></para>
    /// <para>Characters: <c>l1</c>, <c>l2</c>, <c>l3</c>, <c>l4</c></para>
    /// </summary>
    public const string simpleDialogFlow = "268a4c3e-7693-4ce7-8d36-4b0fd2e4a052";

    /// <summary>
    /// <para>Scene: multi-tracks</para>
    /// <para>10 DIALOG</para>
    /// <para>Entry: <c>start_discussion-AI</c></para>
    /// <para>Characters: <c>l1</c>, <c>l2</c>, <c>l3</c>, <c>l4</c></para>
    /// </summary>
    public const string multiTracks = "511c0cba-f9c8-4b9b-a0d1-91a36241a920";

    /// <summary>
    /// <para>Scene: simple-choices</para>
    /// <para>1 CHOICE, 9 DIALOG</para>
    /// <para>Entry: <c>l1_dramatic_intro-AI</c></para>
    /// <para>Characters: <c>l1</c>, <c>l4</c></para>
    /// </summary>
    public const string simpleChoices = "169f7c4c-c3b1-4444-879c-060801cdcb1d";

    /// <summary>
    /// <para>Scene: simple-action</para>
    /// <para>8 ACTION, 1 CHOICE, 11 DIALOG</para>
    /// <para>Entry: <c>l1_alert-AI</c></para>
    /// <para>Characters: <c>boss</c>, <c>l1</c>, <c>l4</c></para>
    /// </summary>
    public const string simpleAction = "7e6e24b7-c08c-452c-9e11-0689d8c17b80";

    /// <summary>
    /// <para>Scene: simple-condition</para>
    /// <para>1 CONDITION, 7 DIALOG</para>
    /// <para>Entry: <c>l1_lost_carrot_distress-AI</c></para>
    /// <para>Characters: <c>l1</c>, <c>l4</c></para>
    /// </summary>
    public const string simpleCondition = "a037a98b-ffec-40d3-8092-4eedb9857501";

    /// <summary>
    /// <para>Scene: condition-dispatch</para>
    /// <para>4 ACTION, 4 CONDITION, 10 DIALOG</para>
    /// <para>Entry: <c>DIALOG-001</c></para>
    /// <para>Characters: <c>l1</c>, <c>l2</c>, <c>l3</c>, <c>l4</c></para>
    /// </summary>
    public const string conditionDispatch = "c2e75db2-85c7-421b-91ab-f7ea1ea45284";

    /// <summary>
    /// <para>Scene: advance-full-demo</para>
    /// <para>1 ACTION, 1 CHOICE, 1 CONDITION, 7 DIALOG</para>
    /// <para>Entry: <c>rally_l4-AI</c></para>
    /// <para>Characters: <c>boss</c>, <c>l1</c>, <c>l2</c>, <c>l3</c>, <c>l4</c></para>
    /// </summary>
    public const string advanceFullDemo = "de99b983-22ee-485a-b668-69677aacfe35";
}

/// <summary>
/// Block identifiers for type-safe access to individual blocks within scenes.
/// Includes block types: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
/// Use these to register callbacks or listeners on specific blocks.
/// Each value maps to the block&apos;s UUID — stable even if the block is renamed.
/// </summary>
public static class LSDE_BLOCKS
{
    /// <summary>
    /// <para>🟦[DIALOG] player_suggestion-AI</para>
    /// <para>"Restons calmes les amis.  Si cette carotte géante est réelle, ce serait le festin du siècle pour tout notre clan.  Si c&apos;..."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_philosophy-AI</c></para>
    /// <para>Out: <c>rabbit_hype-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowPlayerSuggestionAi = "39a5f6d9-59cb-479f-bd17-28bfda31663a";

    /// <summary>
    /// <para>🟦[DIALOG] player_warning-AI</para>
    /// <para>"C&apos;est ça, l3, on essaiera ta technique de distraction métaphysique si on croise un prédateur affamé. En attendant, on av..."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_wisdom-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowPlayerWarningAi = "d13045ac-a103-4e10-acb8-12399c11a2c1";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_hype-AI</para>
    /// <para>"C&apos;est exactement l&apos;esprit d&apos;aventure qu&apos;il nous fallait, l4 !  On va devenir des légendes vivantes, les lapins qui ont d..."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>player_suggestion-AI</c></para>
    /// <para>Out: <c>rabbit_resignation-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitHypeAi = "6ed885e4-eb2d-4916-979d-339a30ae36ae";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_philosophy-AI</para>
    /// <para>"Mais le temps n&apos;est qu&apos;une construction mentale, l2.  Est-ce que la carotte existe vraiment si personne n&apos;est là pour la..."</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_skepticism-AI</c></para>
    /// <para>Out: <c>player_suggestion-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitPhilosophyAi = "067e705a-7696-45da-8a74-16f681dc83a3";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_resignation-AI</para>
    /// <para>"Ton nez nous a déjà conduits dans une mare de boue malodorante la semaine dernière, triple idiot.  Mais bon, je suppose ..."</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_hype-AI</c></para>
    /// <para>Out: <c>rabbit_wisdom-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitResignationAi =
        "cb1663f1-5833-456e-b033-e325d6077d71";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_rumor-AI (entry)</para>
    /// <para>"Les copains, vous n&apos;allez pas me croire, mais j&apos;ai déniché le scoop du siècle : il y aurait une carotte de la taille d&apos;u..."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>Out: <c>rabbit_skepticism-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitRumorAi = "c39d69d1-f508-45a8-8084-09a68f6916e1";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_skepticism-AI</para>
    /// <para>"Encore une de tes inventions débiles, l1 !  La dernière fois, ta fameuse montagne de trèfles n&apos;était qu&apos;un vieux pull ve..."</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_rumor-AI</c></para>
    /// <para>Out: <c>rabbit_philosophy-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitSkepticismAi = "187ddb4f-1321-4255-a3dd-2cef59309af6";

    /// <summary>
    /// <para>🟦[DIALOG] rabbit_wisdom-AI</para>
    /// <para>"Saviez-vous que les renards ne sont que des chiens qui ont fait des études de philosophie ?  Si on leur pose une questio..."</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>simple-dialog-flow</c></para>
    /// <para>In: <c>rabbit_resignation-AI</c></para>
    /// <para>Out: <c>player_warning-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleDialogFlowRabbitWisdomAi = "95144722-b4eb-46c9-ba1e-54434cacda5f";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-001</para>
    /// <para>"hey!"</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>start_discussion-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksDialog001 = "ad8a7573-500c-4038-bfef-a7ed4550ac8e";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-009</para>
    /// <para>"oufff, je pu !!!"</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>noise_2-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksDialog009 = "f38215d6-f0ef-4dc1-bee7-7dccf258ee2a";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-010</para>
    /// <para>"pfff..."</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>l2_response-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksDialog010 = "2b49d688-ae02-43e6-adf0-c57c9ddc6854";

    /// <summary>
    /// <para>🟦[DIALOG] final_decision-AI</para>
    /// <para>"Bref, d&apos;accord pour le terrier nord. Mais si on voit un truc qui aboie, je détale et je ne vous connais plus."</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>l4_comment-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksFinalDecisionAi = "36f0ba66-dfb8-4084-bf10-370a5e6c671b";

    /// <summary>
    /// <para>🟦[DIALOG] l1_irritation-AI</para>
    /// <para>"L3, par pitié, arrête tes bruits débiles ! On essaie d&apos;organiser un casse sérieux là, sois un peu pro."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>l2_response-AI</c></para>
    /// <para>Out: <c>l4_comment-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksL1IrritationAi = "a0f83f4a-271d-468a-821b-a881fe4a6058";

    /// <summary>
    /// <para>🟦[DIALOG] l2_response-AI</para>
    /// <para>"Le terrier nord ? C&apos;est pas là où l&apos;on a croisé ce chien bizarre l&apos;autre jour ? J&apos;ai pas trop envie d&apos;y retourner."</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>noise_1-AI</c></para>
    /// <para>Out: <c>noise_2-AI</c>, <c>l1_irritation-AI</c>, <c>DIALOG-010</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksL2ResponseAi = "be6f47c5-13f3-4c1a-ba43-80d1820067af";

    /// <summary>
    /// <para>🟦[DIALOG] l4_comment-AI</para>
    /// <para>"Il est irrécupérable aujourd&apos;hui, il a encore mangé des baies bizarres près du ruisseau. On ferait mieux de l&apos;ignorer."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>l1_irritation-AI</c></para>
    /// <para>Out: <c>final_decision-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksL4CommentAi = "80bf4972-7375-4b51-829d-d8481ace6b45";

    /// <summary>
    /// <para>🟦[DIALOG] noise_1-AI</para>
    /// <para>"*Scratch scratch scratch* !"</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>start_discussion-AI</c></para>
    /// <para>Out: <c>l2_response-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksNoise1Ai = "7e045b7b-58a0-4b23-a6a0-c24352237680";

    /// <summary>
    /// <para>🟦[DIALOG] noise_2-AI</para>
    /// <para>"*Prout !* Oups, c&apos;était pas moi, c&apos;était le vent ! Ou peut-être mes oreilles qui ont applaudi !"</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>In: <c>l2_response-AI</c></para>
    /// <para>Out: <c>DIALOG-009</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksNoise2Ai = "9ffa9849-4e64-4982-849a-754ee6b67475";

    /// <summary>
    /// <para>🟦[DIALOG] start_discussion-AI (entry)</para>
    /// <para>"Bon, écoutez les gars, pour la carotte géante, il faut qu&apos;on passe par le terrier nord, c&apos;est plus discret."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>multi-tracks</c></para>
    /// <para>Out: <c>noise_1-AI</c>, <c>DIALOG-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string multiTracksStartDiscussionAi = "4604c8d0-c4cb-411a-a878-0d498bae868f";

    /// <summary>
    /// <para>⬜[CHOICE] player_moral_choice-AI</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l1_dramatic_intro-AI</c></para>
    /// <para>Out: <c>l4_brave_response-AI</c>, <c>l4_fear_response-AI</c>, <c>l4_doubt_response-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/choice.webp" />
    /// </remarks>
    public const string simpleChoicesPlayerMoralChoiceAi = "4452e0e5-a494-4e40-b11e-13eee3fb93c7";

    /// <summary>
    /// <para>🟦[DIALOG] l1_brave_reaction-AI</para>
    /// <para>"Ton feu intérieur nous guidera peut-être à travers les ombres qui rampent vers nous."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l4_brave_response-AI</c></para>
    /// <para>Out: <c>l1_final_warning-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL1BraveReactionAi = "b0012922-735a-45ba-b47c-8d9d03725c2c";

    /// <summary>
    /// <para>🟦[DIALOG] l1_doubt_reaction-AI</para>
    /// <para>"Le déni ne changera pas le poids du silence qui s&apos;abat désormais sur la prairie."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l4_doubt_response-AI</c></para>
    /// <para>Out: <c>l1_final_warning-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL1DoubtReactionAi = "d0c0a458-7933-4330-912a-3820ca222ecb";

    /// <summary>
    /// <para>🟦[DIALOG] l1_dramatic_intro-AI (entry)</para>
    /// <para>"Le ciel s&apos;assombrit, l4. La légende de la Carotte Éternelle n&apos;était qu&apos;un prélude à notre chute imminente."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>Out: <c>player_moral_choice-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL1DramaticIntroAi = "1db618cd-3883-4caf-bcd2-591562aade49";

    /// <summary>
    /// <para>🟦[DIALOG] l1_fear_reaction-AI</para>
    /// <para>"La peur est un poison, mais elle est aussi le seul miroir de notre fragile vérité."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l4_fear_response-AI</c></para>
    /// <para>Out: <c>l1_final_warning-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL1FearReactionAi = "50d0c209-6825-4cdd-9085-f8635f125a64";

    /// <summary>
    /// <para>🟦[DIALOG] l1_final_warning-AI</para>
    /// <para>"Écoute... le vent hurle déjà le nom de notre perte. Nous n&apos;avons plus d&apos;autre choix que d&apos;avancer."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l1_brave_reaction-AI</c>, <c>l1_fear_reaction-AI</c>, <c>l1_doubt_reaction-AI</c></para>
    /// <para>Out: <c>l4_final_resolution-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL1FinalWarningAi = "20c774c7-597a-4d02-8730-afa033c20150";

    /// <summary>
    /// <para>🟦[DIALOG] l4_brave_response-AI</para>
    /// <para>"Je ne laisserai personne détruire notre foyer. Je me battrai jusqu&apos;à mon dernier souffle s&apos;il le faut."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>player_moral_choice-AI</c></para>
    /// <para>Out: <c>l1_brave_reaction-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL4BraveResponseAi = "7d80327b-3a65-4be6-b8ed-76cf3cca57ee";

    /// <summary>
    /// <para>🟦[DIALOG] l4_doubt_response-AI</para>
    /// <para>"Tu parles comme un vieux prophète fatigué, l1. Et si ce n&apos;était qu&apos;un simple piège des renards ?"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>player_moral_choice-AI</c></para>
    /// <para>Out: <c>l1_doubt_reaction-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL4DoubtResponseAi = "50dce24b-b3f7-49a6-bfb8-906b7e55a940";

    /// <summary>
    /// <para>🟦[DIALOG] l4_fear_response-AI</para>
    /// <para>"Regarde-nous ! Nous ne sommes que des proies. Espérer vaincre ce destin est une folie pure."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>player_moral_choice-AI</c></para>
    /// <para>Out: <c>l1_fear_reaction-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL4FearResponseAi = "c3b0cdee-d840-4bf4-a0f0-a11d5e6d0402";

    /// <summary>
    /// <para>🟦[DIALOG] l4_final_resolution-AI</para>
    /// <para>"Alors qu&apos;il en soit ainsi. Que le destin nous juge sur le champ de bataille, vers le terrier nord."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// <para>In: <c>l1_final_warning-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleChoicesL4FinalResolutionAi = "b630f2b9-85f5-4e26-aa86-cbc7427e88a1";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-0016</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>focus_boss-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionAction0016 = "fa8ff197-0559-493a-b1a9-b4e0a1724b83";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-006</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>final_decision-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionAction006 = "dfa55271-2ed5-469c-9eaf-a05a46d7b254";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-007</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l4_flee-AI</c></para>
    /// <para>Out: <c>DIALOG-009</c>, <c>DIALOG-010</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionAction007 = "b50008c7-348b-4bf4-b7cd-cec16ae727d0";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-008</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l1_brave-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionAction008 = "26bc6b08-22b3-4ed5-bd6a-d4c955adff63";

    /// <summary>
    /// <para>🟧[ACTION] focus_boss-AI</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>shake_mid-AI</c></para>
    /// <para>Out: <c>boss_roar-AI</c>, <c>ACTION-0016</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionFocusBossAi = "9b5df0e4-0971-4639-8736-9442dcd52d8a";

    /// <summary>
    /// <para>🟧[ACTION] return_to_rabbits-AI</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>DIALOG-007</c></para>
    /// <para>Out: <c>final_decision-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionReturnToRabbitsAi = "4b8b8fe2-d3b8-4ab6-9fc1-afd5eadb78af";

    /// <summary>
    /// <para>🟧[ACTION] shake_intro-AI</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l1_alert-AI</c></para>
    /// <para>Out: <c>l4_terror-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionShakeIntroAi = "6430204d-5833-4fe3-9a5c-499c41c5a5df";

    /// <summary>
    /// <para>🟧[ACTION] shake_mid-AI</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l4_terror-AI</c></para>
    /// <para>Out: <c>focus_boss-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string simpleActionShakeMidAi = "955b54a6-33e9-477a-8573-6ea5dc9d7433";

    /// <summary>
    /// <para>⬜[CHOICE] final_decision-AI</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>return_to_rabbits-AI</c></para>
    /// <para>Out: <c>l1_brave-AI</c>, <c>l4_flee-AI</c>, <c>ACTION-006</c>, <c>DIALOG-008</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/choice.webp" />
    /// </remarks>
    public const string simpleActionFinalDecisionAi = "36cdad6e-d85a-4c9a-90e0-6af5046c4245";

    /// <summary>
    /// <para>🟦[DIALOG] boss_roar-AI</para>
    /// <para>"RWMIAAAOUWWW ...... WROIUMOIWUUWWW...."</para>
    /// <para>Characters: <c>boss</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>focus_boss-AI</c></para>
    /// <para>Out: <c>DIALOG-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionBossRoarAi = "dc58f326-8e8c-4837-beb1-e8ba04410b84";

    /// <summary>
    /// <para>🟦[DIALOG] climax_moment-AI</para>
    /// <para>"whaaaaaaaaaaa"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l1_brave-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionClimaxMomentAi = "b22c8172-a63d-486b-b07d-37ab1832fee6";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-007</para>
    /// <para>"mmmmm !🐰🐰🐰"</para>
    /// <para>Characters: <c>boss</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>boss_roar-AI</c></para>
    /// <para>Out: <c>return_to_rabbits-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionDialog007 = "f12afa3e-7d89-497c-8f2e-585187f3b55a";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-008</para>
    /// <para>"Nom d&apos;une carotte !! Sauve qui peut ! Haaaaa !!!!"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>final_decision-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionDialog008 = "42c00a7a-3954-4e07-9e9e-9254d3a8df64";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-009</para>
    /// <para>"J&apos;aime les carottes, mais pas à ce point !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>ACTION-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionDialog009 = "3c3eb409-7bae-4c79-a1de-637384e51494";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-010</para>
    /// <para>"T&apos;es un gros lapin mouillé, l1... traître !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>ACTION-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionDialog010 = "da5a321e-10b2-44b6-8632-39b737d65a5c";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-011</para>
    /// <para>"whaaaa"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>l1_brave-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionDialog011 = "bce3aa3f-e3e9-4a7e-88a7-a74d5f5a4b58";

    /// <summary>
    /// <para>🟦[DIALOG] l1_alert-AI (entry)</para>
    /// <para>"Est-ce que tu sens ça ? La terre se déchire sous ses pas..."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>Out: <c>shake_intro-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionL1AlertAi = "c3b0ffcf-fe57-45f9-8c20-8db99da21ae3";

    /// <summary>
    /// <para>🟦[DIALOG] l1_brave-AI</para>
    /// <para>"Pour l&apos;honneur du clan et la carotte éternelle, à l&apos;attaque !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>final_decision-AI</c></para>
    /// <para>Out: <c>ACTION-008</c>, <c>climax_moment-AI</c>, <c>DIALOG-011</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionL1BraveAi = "3af36f94-0b76-40dc-9681-1bb360a03897";

    /// <summary>
    /// <para>🟦[DIALOG] l4_flee-AI</para>
    /// <para>"Mais tu ne peux pas me laisser seul !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>final_decision-AI</c></para>
    /// <para>Out: <c>ACTION-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionL4FleeAi = "fca6d66a-a4ea-4059-80ab-9ae2107d6ef9";

    /// <summary>
    /// <para>🟦[DIALOG] l4_terror-AI</para>
    /// <para>"C&apos;est beaucoup trop gros pour être un simple lapin, l1 !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-action</c></para>
    /// <para>In: <c>shake_intro-AI</c></para>
    /// <para>Out: <c>shake_mid-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleActionL4TerrorAi = "38f160eb-9e5f-4dac-b83a-7d0b55afac1a";

    /// <summary>
    /// <para>🟪[CONDITION] check_carrot_inventory-AI</para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>l1_lost_carrot_distress-AI</c></para>
    /// <para>Out: <c>l4_comfort_response-AI</c>, <c>DIALOG-006</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string simpleConditionCheckCarrotInventoryAi =
        "6e270a8d-688c-4101-9d2b-97876b09e301";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-006</para>
    /// <para>"J&apos;ai retrouvé ta carotte !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>check_carrot_inventory-AI</c></para>
    /// <para>Out: <c>l1_carrot_found-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionDialog006 = "d1670c06-ef2f-48db-8fef-df3bb4b63b05";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-007</para>
    /// <para>".... dac"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>l1_carrot_found-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionDialog007 = "7d0cab65-96ed-4471-b7f6-5b060c12007b";

    /// <summary>
    /// <para>🟦[DIALOG] l1_carrot_found-AI</para>
    /// <para>"Tu l&apos;as ! Je sens déjà la chance revenir dans mes oreilles. Tu es mon héros ! Garde la, j&apos;ai trop peur de la perde a nou..."</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>DIALOG-006</c></para>
    /// <para>Out: <c>DIALOG-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionL1CarrotFoundAi = "4d8f4766-5c11-4a5d-bbc7-223a5bc4fc52";

    /// <summary>
    /// <para>🟦[DIALOG] l1_carrot_missing_demand-AI</para>
    /// <para>"Pourquoi restes-tu là à brouter ? Cherche-la sur le champ, avant que le malheur ne nous frappe !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>l4_comfort_response-AI</c></para>
    /// <para>Out: <c>l4_final_thought-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionL1CarrotMissingDemandAi =
        "bde6483a-c9e6-4ca1-94b5-14a8a8e0f36c";

    /// <summary>
    /// <para>🟦[DIALOG] l1_lost_carrot_distress-AI (entry)</para>
    /// <para>"Oh non, ma carotte porte-bonheur a disparu ! Sans elle, c&apos;est sûr, le ciel va nous tomber sur la tête !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>Out: <c>check_carrot_inventory-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionL1LostCarrotDistressAi =
        "cb342290-3616-42d2-ba58-620290dfa45a";

    /// <summary>
    /// <para>🟦[DIALOG] l4_comfort_response-AI</para>
    /// <para>"Calme-toi, l1. Ce n&apos;est qu&apos;une racine séchée. On finira par la retrouver dans ce champ."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>check_carrot_inventory-AI</c></para>
    /// <para>Out: <c>l1_carrot_missing_demand-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionL4ComfortResponseAi = "61ad4724-2845-426f-b4e2-581c670a3c60";

    /// <summary>
    /// <para>🟦[DIALOG] l4_final_thought-AI</para>
    /// <para>"D&apos;accord, d&apos;accord. Ne faisons pas un drame pour un légume, même s&apos;il est porte-bonheur."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>simple-condition</c></para>
    /// <para>In: <c>l1_carrot_missing_demand-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string simpleConditionL4FinalThoughtAi = "1690e771-7627-4abd-9944-84721b40567d";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-001</para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-003</c></para>
    /// <para>Out: <c>DIALOG-007</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string conditionDispatchAction001 = "48e82cd7-1edb-4d11-9a64-8f28c7c0a0a0";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-002</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string conditionDispatchAction002 = "ddd26ce9-3afb-4ca9-891d-86299bf7ff4e";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-003</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string conditionDispatchAction003 = "2211a918-d127-40d0-9dd3-55ec851cc1d2";

    /// <summary>
    /// <para>🟧[ACTION] ACTION-004</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string conditionDispatchAction004 = "035cbe91-d916-4388-b872-e14dbadc191a";

    /// <summary>
    /// <para>🟪[CONDITION] CONDITION-001</para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-002</c></para>
    /// <para>Out: <c>DIALOG-006</c>, <c>DIALOG-003</c>, <c>DIALOG-004</c>, <c>DIALOG-005</c>, <c>ACTION-002</c>, <c>ACTION-003</c>, <c>ACTION-004</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string conditionDispatchCondition001 = "ab111d47-9fe0-41d9-afd9-e96f00a01d9a";

    /// <summary>
    /// <para>🟪[CONDITION] CONDITION-002</para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>DIALOG-001</c></para>
    /// <para>Out: <c>DIALOG-002</c>, <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string conditionDispatchCondition002 = "a004326b-fada-43fd-aae7-f6e1654fa02e";

    /// <summary>
    /// <para>🟪[CONDITION] CONDITION-003</para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>DIALOG-006</c></para>
    /// <para>Out: <c>ACTION-001</c>, <c>DIALOG-008</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string conditionDispatchCondition003 = "164da884-2cd2-4696-b4e0-219bc951cf45";

    /// <summary>
    /// <para>🟪[CONDITION] CONDITION-004</para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>DIALOG-008</c></para>
    /// <para>Out: <c>DIALOG-009</c>, <c>DIALOG-010</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string conditionDispatchCondition004 = "a77ac2c9-ade2-4a5b-b187-4ec81140b885";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-001 (entry)</para>
    /// <para>"« Ô grand esprit des carottes... »"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>Out: <c>CONDITION-002</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog001 = "90a8c0a2-cb0e-4900-b974-c59d470f296e";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-002</para>
    /// <para>"Hey, choisissez-nous avant que nous n&apos;invoquions les esprits de la carotte !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-002</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog002 = "a4610101-f256-4ce8-a622-566493a7ea36";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-003</para>
    /// <para>"Ho, immense carotte rouge éclatante de vie !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog003 = "f0d04478-f078-4284-bb29-84dde7f6745e";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-004</para>
    /// <para>"Ho, vibrante carotte d&apos;un jaune soleil !"</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog004 = "fd4a39f9-6aa7-4222-90b1-7e79f8eab245";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-005</para>
    /// <para>"« Ô grande carotte bleue, nous t&apos;implorons ! »"</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog005 = "802b6469-bf1d-4e17-8bb3-1443b0f32b38";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-006</para>
    /// <para>"Oh grande carotte, merci de nous nourrir !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-001</c></para>
    /// <para>Out: <c>CONDITION-003</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog006 = "f1de0bf3-65d8-4a0f-a26e-31562f349396";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-007</para>
    /// <para>"ca marcher !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>ACTION-001</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog007 = "49711c01-57d5-4776-8bad-6e5b426eb1e8";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-008</para>
    /// <para>"il ce passe rien ! il manque une incantation !? ...."</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-003</c></para>
    /// <para>Out: <c>CONDITION-004</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog008 = "9441ad01-6402-4788-a3e4-0cbc2d2701a3";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-009</para>
    /// <para>"Oui moi"</para>
    /// <para>Characters: <c>l1</c>, <c>l2</c>, <c>l3</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-004</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog009 = "19d77434-b74a-4678-8cd4-859d18c4ec30";

    /// <summary>
    /// <para>🟦[DIALOG] DIALOG-010</para>
    /// <para>"Ho !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>condition-dispatch</c></para>
    /// <para>In: <c>CONDITION-004</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string conditionDispatchDialog010 = "601c1889-5ba1-4da8-8076-f5bc6164c7b5";

    /// <summary>
    /// <para>🟧[ACTION] boss_shake-AI</para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>rally_l4-AI</c></para>
    /// <para>Out: <c>moral_choice-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/action.webp" />
    /// </remarks>
    public const string advanceFullDemoBossShakeAi = "bc141df3-b6d4-4364-bef1-807be344d0ad";

    /// <summary>
    /// <para>⬜[CHOICE] moral_choice-AI</para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>boss_shake-AI</c></para>
    /// <para>Out: <c>l1_join-AI</c>, <c>boss_roar-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/choice.webp" />
    /// </remarks>
    public const string advanceFullDemoMoralChoiceAi = "dbc7c91d-cb29-4aae-ad54-32e500e4987e";

    /// <summary>
    /// <para>🟪[CONDITION] unity_check-AI</para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>l3_join-AI</c></para>
    /// <para>Out: <c>victory_charge-AI</c>, <c>flee_defeat-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/cond.webp" />
    /// </remarks>
    public const string advanceFullDemoUnityCheckAi = "e21578d1-f9eb-46bc-aed3-58dcf2dde1dc";

    /// <summary>
    /// <para>🟦[DIALOG] boss_roar-AI</para>
    /// <para>"RRWAAAAOUHH ! QUI OSE DÉFIER MON RÈGNE POUR UN LÉGUME ?"</para>
    /// <para>Characters: <c>boss</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>moral_choice-AI</c>, <c>flee_defeat-AI</c>, <c>victory_charge-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoBossRoarAi = "c29126e4-9e2f-454e-af5a-47a0b35e6705";

    /// <summary>
    /// <para>🟦[DIALOG] flee_defeat-AI</para>
    /// <para>"On n&apos;est pas assez nombreux ! Sauve qui peut, c&apos;est du suicide !"</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>unity_check-AI</c></para>
    /// <para>Out: <c>boss_roar-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoFleeDefeatAi = "f888d40b-d554-495c-82f3-a1730c6fcc1e";

    /// <summary>
    /// <para>🟦[DIALOG] l1_join-AI</para>
    /// <para>"Si tu as le courage d&apos;y aller, l4, alors mon honneur m&apos;oblige à te suivre !"</para>
    /// <para>Characters: <c>l1</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>moral_choice-AI</c></para>
    /// <para>Out: <c>l2_join-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoL1JoinAi = "d0cae0a6-b684-451f-8e67-ed15c66c209e";

    /// <summary>
    /// <para>🟦[DIALOG] l2_join-AI</para>
    /// <para>"J&apos;ai l&apos;estomac qui crie plus fort que ma peur. Compte sur moi !"</para>
    /// <para>Characters: <c>l2</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>l1_join-AI</c></para>
    /// <para>Out: <c>l3_join-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoL2JoinAi = "9e88280f-b918-4fb5-8ccc-22bd19e91825";

    /// <summary>
    /// <para>🟦[DIALOG] l3_join-AI</para>
    /// <para>"La philosophie enseigne que l&apos;union réduit le néant. Je me joins à vous."</para>
    /// <para>Characters: <c>l3</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>l2_join-AI</c></para>
    /// <para>Out: <c>unity_check-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoL3JoinAi = "bf47afc0-f8bf-4ff2-84ac-a5728421968c";

    /// <summary>
    /// <para>🟦[DIALOG] rally_l4-AI (entry)</para>
    /// <para>"Amis ! La Carotte Éternelle est juste derrière cette bête. On ne peut pas l&apos;abandonner !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>Out: <c>boss_shake-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoRallyL4Ai = "ebf52efe-e48d-4e82-8efe-94a47a783c89";

    /// <summary>
    /// <para>🟦[DIALOG] victory_charge-AI</para>
    /// <para>"Nous sommes au complet ! À l&apos;attaque, mes amis ! Pour la carotte !"</para>
    /// <para>Characters: <c>l4</c></para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// <para>In: <c>unity_check-AI</c></para>
    /// <para>Out: <c>boss_roar-AI</c></para>
    /// </summary>
    /// <remarks>
    /// <image url="./_images/dialog.webp" />
    /// </remarks>
    public const string advanceFullDemoVictoryChargeAi = "4b4c41af-b359-4e2b-88e5-09eeb645f6c3";
}

/// <summary>
/// Choice item identifiers for type-safe access to individual player choices.
/// Each value maps to a choice item&apos;s UUID within a CHOICE block.
/// Use these for switch/case handling of specific player decisions.
/// </summary>
public static class LSDE_CHOICES
{
    /// <summary>
    /// <para>⬜[CHOICE_ITEM] Nous nous battrons !</para>
    /// <para>"Nous nous battrons !"</para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.simpleChoicesPlayerMoralChoiceAi"/></summary>
    public const string simpleChoicesNousNousBattrons = "1db50a61-e40d-49a2-bf02-d8f5eee4ea84";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] C&apos;est un suicide.</para>
    /// <para>"C&apos;est un suicide."</para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.simpleChoicesPlayerMoralChoiceAi"/></summary>
    public const string simpleChoicesCEstUnSuicide = "189ecf6a-3f10-41d5-b4b0-78e35298ee4d";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] Est-ce vraiment réel ?</para>
    /// <para>"Est-ce vraiment réel ?"</para>
    /// <para>Scene: <c>simple-choices</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.simpleChoicesPlayerMoralChoiceAi"/></summary>
    public const string simpleChoicesEstCeVraimentREl = "3716cb04-2e54-4bf4-864d-28b6ce000786";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] Charger la créature !</para>
    /// <para>"Charger la créature !"</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.simpleActionFinalDecisionAi"/></summary>
    public const string simpleActionChargerLaCrAture = "09ccf6a7-35a8-4bec-9468-51728d5b8785";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] Battre en retraite !</para>
    /// <para>"Battre en retraite !"</para>
    /// <para>Scene: <c>simple-action</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.simpleActionFinalDecisionAi"/></summary>
    public const string simpleActionBattreEnRetraite = "cd1ae040-2421-41dd-8962-116a8a13ff78";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] Rallier tout le monde !</para>
    /// <para>"Rallier tout le monde !"</para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.advanceFullDemoMoralChoiceAi"/></summary>
    public const string advanceFullDemoRallierToutLeMonde = "526d2ab5-547b-47ab-a523-f7f1c79663ed";

    /// <summary>
    /// <para>⬜[CHOICE_ITEM] C&apos;est trop dangereux, fuyons !</para>
    /// <para>"C&apos;est trop dangereux, fuyons !"</para>
    /// <para>Scene: <c>advance-full-demo</c></para>
    /// </summary>
    /// <summary>See <see cref="LSDE_BLOCKS.advanceFullDemoMoralChoiceAi"/></summary>
    public const string advanceFullDemoCEstTropDangereuxFuyons =
        "bfbaab42-76ee-4730-b851-e2e37f2bb637";
}
