#pragma warning disable CS8981

// Auto-generated by LSDE. Do not edit manually.
// Identifiers used by LSDEDE-DEMO-TS.blueprints.json: scenes, blocks, options, cards, dictionaries and functions.
// Compare these constants to what the payload carries; never retype the strings.

public static class LsdedeDemoTsBlueprintIds
{
    /// <summary>
    /// <para>Every scene of the payload. The name comes from its path, the VALUE is the id that survives a</para>
    /// <para>rename - store that one wherever a scene is referenced from outside the payload.</para>
    /// </summary>
    public static class Scenes
    {
        /// <summary>
        /// <para>@scene simple-dialog-flow</para>
        /// <para>@start rabbit_rumor-AI</para>
        /// <para>@blocks 8</para>
        /// </summary>
        public const string simpleDialogFlow = "sc_60ql8la3";

        /// <summary>
        /// <para>@scene multi-tracks</para>
        /// <para>@start start_discussion-AI</para>
        /// <para>@blocks 10</para>
        /// </summary>
        public const string multiTracks = "sc_k6owddmj";

        /// <summary>
        /// <para>@scene simple-choices</para>
        /// <para>@start l1_dramatic_intro-AI</para>
        /// <para>@blocks 10</para>
        /// </summary>
        public const string simpleChoices = "sc_nfiw90w6";

        /// <summary>
        /// <para>@scene simple-action</para>
        /// <para>@start l1_alert-AI</para>
        /// <para>@blocks 20</para>
        /// </summary>
        public const string simpleAction = "sc_2oxljar5";

        /// <summary>
        /// <para>@scene simple-condition</para>
        /// <para>@start l1_lost_carrot_distress-AI</para>
        /// <para>@blocks 8</para>
        /// </summary>
        public const string simpleCondition = "sc_u7rz0ucc";

        /// <summary>
        /// <para>@scene condition-dispatch</para>
        /// <para>@start DIALOG-001</para>
        /// <para>@blocks 18</para>
        /// </summary>
        public const string conditionDispatch = "sc_q4c6vbo6";

        /// <summary>
        /// <para>@scene advance-full-demo</para>
        /// <para>@start DIALOG-009</para>
        /// <para>@blocks 20</para>
        /// </summary>
        public const string advanceFullDemo = "sc_pnshhy9t";
    }
    /// <summary>
    /// <para>Every block id, grouped by scene. Ids are relative to their scene: next.to and start use them.</para>
    /// </summary>
    public static class Blocks
    {
        /// <summary>
        /// <para>@scene simple-dialog-flow</para>
        /// </summary>
        public static class simpleDialogFlow
        {
            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Restons calmes les amis. Si cette carotte géante est réelle, ce serait le festin du siècle pour tout notre clan. Si c'es…</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; rabbit_hype-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.player_suggestion-AI</para>
            /// </summary>
            public const string playerSuggestionAi = "player_suggestion-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example C'est ça, l3, on essaiera ta technique de distraction métaphysique si on croise un prédateur affamé. En attendant, on av…</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-dialog-flow.player_warning-AI</para>
            /// </summary>
            public const string playerWarningAi = "player_warning-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example C'est exactement l'esprit d'aventure qu'il nous fallait, l4 ! On va devenir des légendes vivantes, les lapins qui ont dé…</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; rabbit_resignation-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_hype-AI</para>
            /// </summary>
            public const string rabbitHypeAi = "rabbit_hype-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Mais le temps n'est qu'une construction mentale, l2. Est-ce que la carotte existe vraiment si personne n'est là pour la …</para>
            /// <para>@actors l3</para>
            /// <para>@next out -&gt; player_suggestion-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_philosophy-AI</para>
            /// </summary>
            public const string rabbitPhilosophyAi = "rabbit_philosophy-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Ton nez nous a déjà conduits dans une mare de boue malodorante la semaine dernière, triple idiot. Mais bon, je suppose q…</para>
            /// <para>@actors l2</para>
            /// <para>@next out -&gt; rabbit_wisdom-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_resignation-AI</para>
            /// </summary>
            public const string rabbitResignationAi = "rabbit_resignation-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Les copains, vous n'allez pas me croire, mais j'ai déniché le scoop du siècle : il y aurait une carotte de la taille d'u…</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; rabbit_skepticism-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_rumor-AI</para>
            /// </summary>
            public const string rabbitRumorAi = "rabbit_rumor-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Encore une de tes inventions débiles, l1 ! La dernière fois, ta fameuse montagne de trèfles n'était qu'un vieux pull ver…</para>
            /// <para>@actors l2</para>
            /// <para>@next out -&gt; rabbit_philosophy-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_skepticism-AI</para>
            /// </summary>
            public const string rabbitSkepticismAi = "rabbit_skepticism-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Saviez-vous que les renards ne sont que des chiens qui ont fait des études de philosophie ? Si on leur pose une question…</para>
            /// <para>@actors l3</para>
            /// <para>@next out -&gt; player_warning-AI</para>
            /// <para>@key __blueprints__.simple-dialog-flow.rabbit_wisdom-AI</para>
            /// </summary>
            public const string rabbitWisdomAi = "rabbit_wisdom-AI";
        }
        /// <summary>
        /// <para>@scene multi-tracks</para>
        /// </summary>
        public static class multiTracks
        {
            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example hey!</para>
            /// <para>@actors l3</para>
            /// <para>@key __blueprints__.multi-tracks.DIALOG-001</para>
            /// </summary>
            public const string dialog001 = "DIALOG-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example oufff, je pu !!!</para>
            /// <para>@actors l3</para>
            /// <para>@key __blueprints__.multi-tracks.DIALOG-009</para>
            /// </summary>
            public const string dialog009 = "DIALOG-009";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example pfff...</para>
            /// <para>@actors l2</para>
            /// <para>@key __blueprints__.multi-tracks.DIALOG-010</para>
            /// </summary>
            public const string dialog010 = "DIALOG-010";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Bref, d'accord pour le terrier nord. Mais si on voit un truc qui aboie, je détale et je ne vous connais plus.</para>
            /// <para>@actors l2</para>
            /// <para>@key __blueprints__.multi-tracks.final_decision-AI</para>
            /// </summary>
            public const string finalDecisionAi = "final_decision-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example L3, par pitié, arrête tes bruits débiles ! On essaie d'organiser un casse sérieux là, sois un peu pro.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l4_comment-AI</para>
            /// <para>@key __blueprints__.multi-tracks.l1_irritation-AI</para>
            /// </summary>
            public const string l1IrritationAi = "l1_irritation-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Le terrier nord ? C'est pas là où l'on a croisé ce chien bizarre l'autre jour ? J'ai pas trop envie d'y retourner.</para>
            /// <para>@actors l2</para>
            /// <para>@next out -&gt; noise_2-AI, out -&gt; l1_irritation-AI, out -&gt; DIALOG-010</para>
            /// <para>@key __blueprints__.multi-tracks.l2_response-AI</para>
            /// </summary>
            public const string l2ResponseAi = "l2_response-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Il est irrécupérable aujourd'hui, il a encore mangé des baies bizarres près du ruisseau. On ferait mieux de l'ignorer.</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; final_decision-AI</para>
            /// <para>@key __blueprints__.multi-tracks.l4_comment-AI</para>
            /// </summary>
            public const string l4CommentAi = "l4_comment-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example *Scratch scratch scratch* !</para>
            /// <para>@actors l2</para>
            /// <para>@next out -&gt; l2_response-AI</para>
            /// <para>@key __blueprints__.multi-tracks.noise_1-AI</para>
            /// </summary>
            public const string noise1Ai = "noise_1-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example *Prout !* Oups, c'était pas moi, c'était le vent ! Ou peut-être mes oreilles qui ont applaudi !</para>
            /// <para>@actors l3</para>
            /// <para>@next out -&gt; DIALOG-009</para>
            /// <para>@key __blueprints__.multi-tracks.noise_2-AI</para>
            /// </summary>
            public const string noise2Ai = "noise_2-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Bon, écoutez les gars, pour la carotte géante, il faut qu'on passe par le terrier nord, c'est plus discret.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; noise_1-AI, out -&gt; DIALOG-001</para>
            /// <para>@key __blueprints__.multi-tracks.start_discussion-AI</para>
            /// </summary>
            public const string startDiscussionAi = "start_discussion-AI";
        }
        /// <summary>
        /// <para>@scene simple-choices</para>
        /// </summary>
        public static class simpleChoices
        {
            /// <summary>
            /// <para>@type choice</para>
            /// <para>@actors l4</para>
            /// <para>@options C1, C2, C3</para>
            /// <para>@next C1 -&gt; l4_brave_response-AI, C2 -&gt; l4_fear_response-AI, C3 -&gt; l4_doubt_response-AI</para>
            /// <para>@note Nous nous battrons ! | C'est un suicide. | Est-ce vraiment réel ?</para>
            /// <para>@key __blueprints__.simple-choices.player_moral_choice-AI</para>
            /// </summary>
            public const string playerMoralChoiceAi = "player_moral_choice-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Ton feu intérieur nous guidera peut-être à travers les ombres qui rampent vers nous.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l1_final_warning-AI</para>
            /// <para>@key __blueprints__.simple-choices.l1_brave_reaction-AI</para>
            /// </summary>
            public const string l1BraveReactionAi = "l1_brave_reaction-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Le déni ne changera pas le poids du silence qui s'abat désormais sur la prairie.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l1_final_warning-AI</para>
            /// <para>@key __blueprints__.simple-choices.l1_doubt_reaction-AI</para>
            /// </summary>
            public const string l1DoubtReactionAi = "l1_doubt_reaction-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Le ciel s'assombrit, l4. La légende de la Carotte Éternelle n'était qu'un prélude à notre chute imminente.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; player_moral_choice-AI</para>
            /// <para>@key __blueprints__.simple-choices.l1_dramatic_intro-AI</para>
            /// </summary>
            public const string l1DramaticIntroAi = "l1_dramatic_intro-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example La peur est un poison, mais elle est aussi le seul miroir de notre fragile vérité.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l1_final_warning-AI</para>
            /// <para>@key __blueprints__.simple-choices.l1_fear_reaction-AI</para>
            /// </summary>
            public const string l1FearReactionAi = "l1_fear_reaction-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Écoute... le vent hurle déjà le nom de notre perte. Nous n'avons plus d'autre choix que d'avancer.</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l4_final_resolution-AI</para>
            /// <para>@key __blueprints__.simple-choices.l1_final_warning-AI</para>
            /// </summary>
            public const string l1FinalWarningAi = "l1_final_warning-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Je ne laisserai personne détruire notre foyer. Je me battrai jusqu'à mon dernier souffle s'il le faut.</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; l1_brave_reaction-AI</para>
            /// <para>@key __blueprints__.simple-choices.l4_brave_response-AI</para>
            /// </summary>
            public const string l4BraveResponseAi = "l4_brave_response-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Tu parles comme un vieux prophète fatigué, l1. Et si ce n'était qu'un simple piège des renards ?</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; l1_doubt_reaction-AI</para>
            /// <para>@key __blueprints__.simple-choices.l4_doubt_response-AI</para>
            /// </summary>
            public const string l4DoubtResponseAi = "l4_doubt_response-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Regarde-nous ! Nous ne sommes que des proies. Espérer vaincre ce destin est une folie pure.</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; l1_fear_reaction-AI</para>
            /// <para>@key __blueprints__.simple-choices.l4_fear_response-AI</para>
            /// </summary>
            public const string l4FearResponseAi = "l4_fear_response-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Alors qu'il en soit ainsi. Que le destin nous juge sur le champ de bataille, vers le terrier nord.</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-choices.l4_final_resolution-AI</para>
            /// </summary>
            public const string l4FinalResolutionAi = "l4_final_resolution-AI";
        }
        /// <summary>
        /// <para>@scene simple-action</para>
        /// </summary>
        public static class simpleAction
        {
            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls shakeCamera</para>
            /// <para>@note shakeCamera(8, 0.8)</para>
            /// <para>@key __blueprints__.simple-action.ACTION-0016</para>
            /// </summary>
            public const string action0016 = "ACTION-0016";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls shakeCamera, moveCharacterAt</para>
            /// <para>@key __blueprints__.simple-action.ACTION-006</para>
            /// </summary>
            public const string action006 = "ACTION-006";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCameraToLabel</para>
            /// <para>@next then -&gt; DIALOG-009, then -&gt; DIALOG-010</para>
            /// <para>@note moveCameraToLabel(l1)</para>
            /// <para>@key __blueprints__.simple-action.ACTION-007</para>
            /// </summary>
            public const string action007 = "ACTION-007";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCameraToLabel, moveCharacterAt</para>
            /// <para>@key __blueprints__.simple-action.ACTION-008</para>
            /// </summary>
            public const string action008 = "ACTION-008";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCameraToLabel</para>
            /// <para>@next then -&gt; boss_roar-AI, then -&gt; ACTION-0016</para>
            /// <para>@note moveCameraToLabel(boss)</para>
            /// <para>@key __blueprints__.simple-action.focus_boss-AI</para>
            /// </summary>
            public const string focusBossAi = "focus_boss-AI";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCameraToLabel</para>
            /// <para>@next then -&gt; final_decision-AI</para>
            /// <para>@note moveCameraToLabel(l1)</para>
            /// <para>@key __blueprints__.simple-action.return_to_rabbits-AI</para>
            /// </summary>
            public const string returnToRabbitsAi = "return_to_rabbits-AI";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls shakeCamera</para>
            /// <para>@next then -&gt; l4_terror-AI</para>
            /// <para>@note shakeCamera(5, 0.5)</para>
            /// <para>@key __blueprints__.simple-action.shake_intro-AI</para>
            /// </summary>
            public const string shakeIntroAi = "shake_intro-AI";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls shakeCamera</para>
            /// <para>@next then -&gt; focus_boss-AI</para>
            /// <para>@note shakeCamera(8, 0.8)</para>
            /// <para>@key __blueprints__.simple-action.shake_mid-AI</para>
            /// </summary>
            public const string shakeMidAi = "shake_mid-AI";

            /// <summary>
            /// <para>@type choice</para>
            /// <para>@options C1, C2</para>
            /// <para>@next C1 -&gt; l1_brave-AI, C2 -&gt; l4_flee-AI, C2 -&gt; ACTION-006, C2 -&gt; DIALOG-008</para>
            /// <para>@note Charger la créature ! | Battre en retraite !</para>
            /// <para>@key __blueprints__.simple-action.final_decision-AI</para>
            /// </summary>
            public const string finalDecisionAi = "final_decision-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example RWMIAAAOUWWW ...... WROIUMOIWUUWWW....</para>
            /// <para>@actors boss</para>
            /// <para>@next out -&gt; DIALOG-007</para>
            /// <para>@key __blueprints__.simple-action.boss_roar-AI</para>
            /// </summary>
            public const string bossRoarAi = "boss_roar-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example whaaaaaaaaaaa</para>
            /// <para>@actors l1</para>
            /// <para>@key __blueprints__.simple-action.climax_moment-AI</para>
            /// </summary>
            public const string climaxMomentAi = "climax_moment-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example mmmmm !🐰🐰🐰</para>
            /// <para>@actors boss</para>
            /// <para>@next out -&gt; return_to_rabbits-AI</para>
            /// <para>@key __blueprints__.simple-action.DIALOG-007</para>
            /// </summary>
            public const string dialog007 = "DIALOG-007";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Nom d'une carotte !! Sauve qui peut ! Haaaaa !!!!</para>
            /// <para>@actors l1</para>
            /// <para>@key __blueprints__.simple-action.DIALOG-008</para>
            /// </summary>
            public const string dialog008 = "DIALOG-008";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example J'aime les carottes, mais pas à ce point !</para>
            /// <para>@actors l1</para>
            /// <para>@key __blueprints__.simple-action.DIALOG-009</para>
            /// </summary>
            public const string dialog009 = "DIALOG-009";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example T'es un gros lapin mouillé, l1... traître !</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-action.DIALOG-010</para>
            /// </summary>
            public const string dialog010 = "DIALOG-010";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example whaaaa</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-action.DIALOG-011</para>
            /// </summary>
            public const string dialog011 = "DIALOG-011";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Est-ce que tu sens ça ? La terre se déchire sous ses pas...</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; shake_intro-AI</para>
            /// <para>@key __blueprints__.simple-action.l1_alert-AI</para>
            /// </summary>
            public const string l1AlertAi = "l1_alert-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Pour l'honneur du clan et la carotte éternelle, à l'attaque !</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; ACTION-008, out -&gt; climax_moment-AI, out -&gt; DIALOG-011</para>
            /// <para>@key __blueprints__.simple-action.l1_brave-AI</para>
            /// </summary>
            public const string l1BraveAi = "l1_brave-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Mais tu ne peux pas me laisser seul !</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; ACTION-007</para>
            /// <para>@key __blueprints__.simple-action.l4_flee-AI</para>
            /// </summary>
            public const string l4FleeAi = "l4_flee-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example C'est beaucoup trop gros pour être un simple lapin, l1 !</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; shake_mid-AI</para>
            /// <para>@key __blueprints__.simple-action.l4_terror-AI</para>
            /// </summary>
            public const string l4TerrorAi = "l4_terror-AI";
        }
        /// <summary>
        /// <para>@scene simple-condition</para>
        /// </summary>
        public static class simpleCondition
        {
            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next default -&gt; l4_comfort_response-AI, out -&gt; DIALOG-006</para>
            /// <para>@note inventory.carrot &gt;= 1</para>
            /// <para>@key __blueprints__.simple-condition.check_carrot_inventory-AI</para>
            /// </summary>
            public const string checkCarrotInventoryAi = "check_carrot_inventory-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example J'ai retrouvé ta carotte !</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; l1_carrot_found-AI</para>
            /// <para>@key __blueprints__.simple-condition.DIALOG-006</para>
            /// </summary>
            public const string dialog006 = "DIALOG-006";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example .... dac</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-condition.DIALOG-007</para>
            /// </summary>
            public const string dialog007 = "DIALOG-007";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Tu l'as ! Je sens déjà la chance revenir dans mes oreilles. Tu es mon héros ! Garde la, j'ai trop peur de la perde a nou…</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; DIALOG-007</para>
            /// <para>@key __blueprints__.simple-condition.l1_carrot_found-AI</para>
            /// </summary>
            public const string l1CarrotFoundAi = "l1_carrot_found-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Pourquoi restes-tu là à brouter ? Cherche-la sur le champ, avant que le malheur ne nous frappe !</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; l4_final_thought-AI</para>
            /// <para>@key __blueprints__.simple-condition.l1_carrot_missing_demand-AI</para>
            /// </summary>
            public const string l1CarrotMissingDemandAi = "l1_carrot_missing_demand-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Oh non, ma carotte porte-bonheur a disparu ! Sans elle, c'est sûr, le ciel va nous tomber sur la tête !</para>
            /// <para>@actors l1</para>
            /// <para>@next out -&gt; check_carrot_inventory-AI</para>
            /// <para>@key __blueprints__.simple-condition.l1_lost_carrot_distress-AI</para>
            /// </summary>
            public const string l1LostCarrotDistressAi = "l1_lost_carrot_distress-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Calme-toi, l1. Ce n'est qu'une racine séchée. On finira par la retrouver dans ce champ.</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; l1_carrot_missing_demand-AI</para>
            /// <para>@key __blueprints__.simple-condition.l4_comfort_response-AI</para>
            /// </summary>
            public const string l4ComfortResponseAi = "l4_comfort_response-AI";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example D'accord, d'accord. Ne faisons pas un drame pour un légume, même s'il est porte-bonheur.</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.simple-condition.l4_final_thought-AI</para>
            /// </summary>
            public const string l4FinalThoughtAi = "l4_final_thought-AI";
        }
        /// <summary>
        /// <para>@scene condition-dispatch</para>
        /// </summary>
        public static class conditionDispatch
        {
            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls shakeCamera</para>
            /// <para>@next then -&gt; DIALOG-007</para>
            /// <para>@key __blueprints__.condition-dispatch.ACTION-001</para>
            /// </summary>
            public const string action001 = "ACTION-001";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@actors l1</para>
            /// <para>@calls moveCharacterAt</para>
            /// <para>@key __blueprints__.condition-dispatch.ACTION-002</para>
            /// </summary>
            public const string action002 = "ACTION-002";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@actors l1</para>
            /// <para>@calls moveCharacterAt</para>
            /// <para>@key __blueprints__.condition-dispatch.ACTION-003</para>
            /// </summary>
            public const string action003 = "ACTION-003";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@actors l1</para>
            /// <para>@calls moveCharacterAt</para>
            /// <para>@key __blueprints__.condition-dispatch.ACTION-004</para>
            /// </summary>
            public const string action004 = "ACTION-004";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next default -&gt; DIALOG-002, out -&gt; ROUTER-001</para>
            /// <para>@key __blueprints__.condition-dispatch.CONDITION-002</para>
            /// </summary>
            public const string condition002 = "CONDITION-002";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next out -&gt; ACTION-001, default -&gt; DIALOG-008</para>
            /// <para>@key __blueprints__.condition-dispatch.CONDITION-003</para>
            /// </summary>
            public const string condition003 = "CONDITION-003";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example « Ô grand esprit des carottes... »</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; CONDITION-002</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-001</para>
            /// </summary>
            public const string dialog001 = "DIALOG-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Hey, choisissez-nous avant que nous n'invoquions les esprits de la carotte !</para>
            /// <para>@actors l1</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-002</para>
            /// </summary>
            public const string dialog002 = "DIALOG-002";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Ho, immense carotte rouge éclatante de vie !</para>
            /// <para>@actors l1</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-003</para>
            /// </summary>
            public const string dialog003 = "DIALOG-003";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Ho, vibrante carotte d'un jaune soleil !</para>
            /// <para>@actors l2</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-004</para>
            /// </summary>
            public const string dialog004 = "DIALOG-004";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example « Ô grande carotte bleue, nous t'implorons ! »</para>
            /// <para>@actors l3</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-005</para>
            /// </summary>
            public const string dialog005 = "DIALOG-005";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Oh grande carotte, merci de nous nourrir !</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; CONDITION-003</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-006</para>
            /// </summary>
            public const string dialog006 = "DIALOG-006";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example ca marcher !</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-007</para>
            /// </summary>
            public const string dialog007 = "DIALOG-007";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example il ce passe rien ! il manque une incantation !? ....</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; ROUTER-002</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-008</para>
            /// </summary>
            public const string dialog008 = "DIALOG-008";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Oui moi</para>
            /// <para>@actors l1, l2, l3</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-009</para>
            /// </summary>
            public const string dialog009 = "DIALOG-009";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Ho !</para>
            /// <para>@actors l4</para>
            /// <para>@key __blueprints__.condition-dispatch.DIALOG-010</para>
            /// </summary>
            public const string dialog010 = "DIALOG-010";

            /// <summary>
            /// <para>@type router</para>
            /// <para>@next catch -&gt; DIALOG-006, K1 -&gt; DIALOG-003, K2 -&gt; DIALOG-004, K3 -&gt; DIALOG-005, K1 -&gt; ACTION-002, K2 -&gt; ACTION-003, K3 -&gt; ACTION-004</para>
            /// <para>@key __blueprints__.condition-dispatch.ROUTER-001</para>
            /// </summary>
            public const string router001 = "ROUTER-001";

            /// <summary>
            /// <para>@type router</para>
            /// <para>@next catch -&gt; DIALOG-010, K1 -&gt; DIALOG-009, K2 -&gt; DIALOG-009, K3 -&gt; DIALOG-009</para>
            /// <para>@key __blueprints__.condition-dispatch.ROUTER-002</para>
            /// </summary>
            public const string router002 = "ROUTER-002";
        }
        /// <summary>
        /// <para>@scene advance-full-demo</para>
        /// </summary>
        public static class advanceFullDemo
        {
            /// <summary>
            /// <para>@type note</para>
            /// <para>@note LE CLOU DU SPECTACLE — les quatre lapins devant la Carotte Éternelle, gardée par la bête endormie. l4 refuse d'attaquer …</para>
            /// <para>@key __blueprints__.advance-full-demo.NOTE-001</para>
            /// </summary>
            public const string note001 = "NOTE-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example Silence dans les rangs. La voilà... la Carotte Suprême. Et ce lièvre géant roupille juste devant. Que personne ne claque…</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; ACTION-003, out -&gt; DIALOG-010, out -&gt; DIALOG-011</para>
            /// <para>@note l4 vient de déboucher du terrier et découvre la Carotte Éternelle, la bête endormie juste devant. Il impose le silence à…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-009</para>
            /// </summary>
            public const string dialog009 = "DIALOG-009";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCameraToLabel, shakeCamera</para>
            /// <para>@note La caméra glisse sur la bête pendant que les lapins chuchotent, et le sol tremble sous son ronflement. Piste parallèle q…</para>
            /// <para>@key __blueprints__.advance-full-demo.ACTION-003</para>
            /// </summary>
            public const string action003 = "ACTION-003";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Dilemme métaphysique : s'il rêve de carottes, son sommeil a-t-il plus de valeur nutritive que notre réalité ?</para>
            /// <para>@actors l3</para>
            /// <para>@note l3 philosophe à voix basse, comme d'habitude, sans attendre son tour. Deuxième piste parallèle : elle s'abandonne au bou…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-010</para>
            /// </summary>
            public const string dialog010 = "DIALOG-010";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example {{@l3}}, tais-toi ! Point d'étape avant l'assaut : est-ce que tout le terrier est là, et combien de carottes on a en rés…</para>
            /// <para>@actors l2</para>
            /// <para>@next out -&gt; COND-005</para>
            /// <para>@note l2 coupe court à la philosophie et pose les deux seules questions qui comptent avant d'attaquer : qui est là, et ce qu'o…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-011</para>
            /// </summary>
            public const string dialog011 = "DIALOG-011";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Incroyable. Vous êtes tous restés plantés derrière ? Je suis tout seul face à une boule de poils de trois cents kilos !</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; DIALOG-013</para>
            /// <para>@note Personne n'a suivi : l4 est seul devant la bête et n'entend que ceux qui l'appellent de loin. Sortie « then » du diffuse…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-012</para>
            /// </summary>
            public const string dialog012 = "DIALOG-012";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Équipe incomplète ou stock insuffisant : c'est le suicide assuré. Demi-tour, on rassemble tout le monde et on réessaie !</para>
            /// <para>@actors l4</para>
            /// <para>@note l4 renvoie tout le monde chercher ce qui manque plutôt que d'attaquer à moitié. Sortie « catch » du diffuseur — au moins…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-013</para>
            /// </summary>
            public const string dialog013 = "DIALOG-013";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Hé, m'abandonnez pas ! Mes pattes sont coincées dans un terrier !</para>
            /// <para>@actors l1, l2, l3</para>
            /// <para>@note Celui qui manque crie depuis l'endroit où il est resté en arrière, et il n'est pas forcément seul : le diffuseur lance u…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-015</para>
            /// </summary>
            public const string dialog015 = "DIALOG-015";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Impeccable. Les troupes sont au complet et le sac déborde de carottes. C'est l'heure : quelle stratégie on adopte contre…</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; CHOICE-003</para>
            /// <para>@note l4 constate que l'équipe est au complet et que le sac n'est pas vide, et prend la responsabilité du plan. Sortie du cas …</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-016</para>
            /// </summary>
            public const string dialog016 = "DIALOG-016";

            /// <summary>
            /// <para>@type choice</para>
            /// <para>@options C1, C2, C3</para>
            /// <para>@next C1 -&gt; ACTION-004, C2 -&gt; DIALOG-018, C3 -&gt; DIALOG-019, C2 -&gt; ACTION-005</para>
            /// <para>@note Le joueur décide comment franchir la bête. Trois options, trois ports — et la scène RETIENDRA la réponse : un aiguillage…</para>
            /// <para>@key __blueprints__.advance-full-demo.CHOICE-003</para>
            /// </summary>
            public const string choice003 = "CHOICE-003";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls moveCharacterAt, shakeCamera</para>
            /// <para>@next then -&gt; COND-004</para>
            /// <para>@note l1 s'avance de quelques pas et lance sa carotte de toutes ses forces ; la bête bouge et le sol tremble. Action à deux ap…</para>
            /// <para>@key __blueprints__.advance-full-demo.ACTION-004</para>
            /// </summary>
            public const string action004 = "ACTION-004";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example POUR L'HONNEUR DU CLAN ET LA VITAMINE A !</para>
            /// <para>@actors l1, l2, l4</para>
            /// <para>@note Les trois se jettent en avant en criant la même chose. SORTIE PAR PERSONNAGE : le bloc a un port par lapin plus un « sin…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-018</para>
            /// </summary>
            public const string dialog018 = "DIALOG-018";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Salutations, colosse. Réfléchis bien : garder un légume que tu ne manges jamais fait-il de toi un protecteur ou un otage…</para>
            /// <para>@actors l3</para>
            /// <para>@next out -&gt; COND-004</para>
            /// <para>@note l3 pose à la bête exactement le genre de question dont il disait, au début de l'aventure, qu'elle endort les prédateurs …</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-019</para>
            /// </summary>
            public const string dialog019 = "DIALOG-019";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next K1 -&gt; DIALOG-020, default -&gt; DIALOG-021</para>
            /// <para>@note La bête réagit selon ce qui vient d'être tenté. L'aiguillage relit LA RÉPONSE DU JOUEUR au choix plus haut — la mémoire …</para>
            /// <para>@key __blueprints__.advance-full-demo.COND-004</para>
            /// </summary>
            public const string cond004 = "COND-004";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example ...otage... devoir... carotte ontologique... zzzzz...</para>
            /// <para>@actors boss</para>
            /// <para>@note La bête s'endort en essayant de résoudre la question, exactement comme l3 l'avait annoncé pour les renards. Fin de la sc…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-020</para>
            /// </summary>
            public const string dialog020 = "DIALOG-020";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example GROUAAARGH ! MAUDITS LAPINS, JE VAIS VOUS RÉDUIRE EN COMPOTE !</para>
            /// <para>@actors boss</para>
            /// <para>@next out -&gt; CHOICE-003</para>
            /// <para>@note La bête se réveille furieuse et tout le monde recule jusqu'à sa place de départ. Son fil REMONTE vers le choix : le joue…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-021</para>
            /// </summary>
            public const string dialog021 = "DIALOG-021";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next K1 -&gt; DIALOG-016, default -&gt; DIALOG-022</para>
            /// <para>@note l4 compte son monde et ses vivres avant de lancer quoi que ce soit : il ne bouge pas tant que les trois autres ne sont p…</para>
            /// <para>@key __blueprints__.advance-full-demo.COND-005</para>
            /// </summary>
            public const string cond005 = "COND-005";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Halte ! On ne défie pas un colosse pareil sans une escouade complète et assez de provisions. Faisons le point.</para>
            /// <para>@actors l4</para>
            /// <para>@next out -&gt; ROUTER-004</para>
            /// <para>@note l4 refuse de lancer l'assaut tant qu'il manque quelqu'un ou quelque chose. Repli de l'aiguillage : c'est le chemin qu'on…</para>
            /// <para>@key __blueprints__.advance-full-demo.DIALOG-022</para>
            /// </summary>
            public const string dialog022 = "DIALOG-022";

            /// <summary>
            /// <para>@type router</para>
            /// <para>@next K1 -&gt; DIALOG-015, K2 -&gt; DIALOG-015, K3 -&gt; DIALOG-015, then -&gt; DIALOG-012, catch -&gt; DIALOG-013</para>
            /// <para>@note Chacun de ceux qui manquent se signale depuis l'endroit où il est resté, tous en même temps, et chaque cas entre par la …</para>
            /// <para>@key __blueprints__.advance-full-demo.ROUTER-004</para>
            /// </summary>
            public const string router004 = "ROUTER-004";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@actors l1, l2, l4</para>
            /// <para>@calls moveCharacterAt, moveCharacterAt, moveCharacterAt, moveCameraToLabel</para>
            /// <para>@key __blueprints__.advance-full-demo.ACTION-005</para>
            /// </summary>
            public const string action005 = "ACTION-005";
        }
    }
    /// <summary>
    /// <para>Every option id, grouped by scene then by choice block. An option id is also its exit port.</para>
    /// </summary>
    public static class Options
    {
        /// <summary>
        /// <para>@scene simple-choices</para>
        /// </summary>
        public static class simpleChoices
        {
            /// <summary>
            /// <para>@block player_moral_choice-AI</para>
            /// </summary>
            public static class playerMoralChoiceAi
            {
                /// <summary>
                /// <para>@example Nous nous battrons !</para>
                /// <para>@key __blueprints__.simple-choices.player_moral_choice-AI.C1</para>
                /// </summary>
                public const string c1 = "C1";

                /// <summary>
                /// <para>@example C'est un suicide.</para>
                /// <para>@key __blueprints__.simple-choices.player_moral_choice-AI.C2</para>
                /// </summary>
                public const string c2 = "C2";

                /// <summary>
                /// <para>@example Est-ce vraiment réel ?</para>
                /// <para>@key __blueprints__.simple-choices.player_moral_choice-AI.C3</para>
                /// </summary>
                public const string c3 = "C3";
            }
        }
        /// <summary>
        /// <para>@scene simple-action</para>
        /// </summary>
        public static class simpleAction
        {
            /// <summary>
            /// <para>@block final_decision-AI</para>
            /// </summary>
            public static class finalDecisionAi
            {
                /// <summary>
                /// <para>@example Charger la créature !</para>
                /// <para>@key __blueprints__.simple-action.final_decision-AI.C1</para>
                /// </summary>
                public const string c1 = "C1";

                /// <summary>
                /// <para>@example Battre en retraite !</para>
                /// <para>@key __blueprints__.simple-action.final_decision-AI.C2</para>
                /// </summary>
                public const string c2 = "C2";
            }
        }
        /// <summary>
        /// <para>@scene advance-full-demo</para>
        /// </summary>
        public static class advanceFullDemo
        {
            /// <summary>
            /// <para>@block CHOICE-003</para>
            /// </summary>
            public static class choice003
            {
                /// <summary>
                /// <para>@example Lancer une carotte pour faire diversion</para>
                /// <para>@key __blueprints__.advance-full-demo.CHOICE-003.C1</para>
                /// </summary>
                public const string c1 = "C1";

                /// <summary>
                /// <para>@example Charger en hurlant tous ensemble</para>
                /// <para>@key __blueprints__.advance-full-demo.CHOICE-003.C2</para>
                /// </summary>
                public const string c2 = "C2";

                /// <summary>
                /// <para>@example Envoyer {{@l3}} lui parler d'existentialisme</para>
                /// <para>@key __blueprints__.advance-full-demo.CHOICE-003.C3</para>
                /// </summary>
                public const string c3 = "C3";
            }
        }
    }
    /// <summary>
    /// <para>Every card the blocks may cite, under its game name. The value is the id that actors carries.</para>
    /// </summary>
    public static class Cards
    {
        /// <summary>
        /// <para>@name l1</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string l1 = "0d848982-9b5e-4437-b0d7-96a97ae78538";

        /// <summary>
        /// <para>@name l2</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string l2 = "0d9e2f0f-7382-439e-a256-8a29e65bdc09";

        /// <summary>
        /// <para>@name l3</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string l3 = "0f16b34e-f9d5-493f-8bbc-8a2d1418f221";

        /// <summary>
        /// <para>@name l4</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string l4 = "60383860-3694-4f1e-9ae4-c1b5bdc9d842";

        /// <summary>
        /// <para>@name boss</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string boss = "1cd35781-e3b7-47b3-bc2b-76b1a2424eba";
    }
    /// <summary>
    /// <para>Every dictionary id, as ConditionTest.dict cites it.</para>
    /// </summary>
    public static class Dictionaries
    {
        /// <summary>
        /// <para>@type number</para>
        /// <para>@entries 1</para>
        /// </summary>
        public const string inventory = "inventory";

        /// <summary>
        /// <para>@type boolean</para>
        /// <para>@entries 3</para>
        /// </summary>
        public const string party = "party";

        /// <summary>
        /// <para>@type string</para>
        /// <para>@entries 3</para>
        /// </summary>
        public const string moveCameraToLabelId = "moveCameraToLabel_id";
    }
    /// <summary>
    /// <para>Every entry key, grouped by dictionary: what ConditionTest.entry cites.</para>
    /// </summary>
    public static class DictionaryEntries
    {
        /// <summary>
        /// <para>@dictionary inventory</para>
        /// <para>@type number</para>
        /// </summary>
        public static class inventory
        {
            public const string carrot = "carrot";
        }
        /// <summary>
        /// <para>@dictionary party</para>
        /// <para>@type boolean</para>
        /// </summary>
        public static class party
        {
            public const string l1 = "l1";
            public const string l2 = "l2";
            public const string l3 = "l3";
        }
        /// <summary>
        /// <para>@dictionary moveCameraToLabel_id</para>
        /// <para>@type string</para>
        /// </summary>
        public static class moveCameraToLabelId
        {
            public const string boss = "boss";
            public const string l4 = "l4";
            public const string l1 = "l1";
        }
    }
    /// <summary>
    /// <para>Every engine function id, as ActionCall.fn names it.</para>
    /// </summary>
    public static class Functions
    {
        /// <summary>
        /// <para>@params id: dictionaryKey(moveCameraToLabel_id), duration: number</para>
        /// </summary>
        public const string moveCameraToLabel = "moveCameraToLabel";

        /// <summary>
        /// <para>@params intensity: number, duration: number</para>
        /// </summary>
        public const string shakeCamera = "shakeCamera";

        /// <summary>
        /// <para>@params id: dictionaryKey(party), x: number, y: number, absolut: boolean</para>
        /// </summary>
        public const string moveCharacterAt = "moveCharacterAt";
    }
    /// <summary>
    /// <para>Every parameter name, grouped by function: the keys of ActionCall.args.</para>
    /// </summary>
    public static class FunctionParams
    {
        /// <summary>
        /// <para>@function moveCameraToLabel</para>
        /// </summary>
        public static class moveCameraToLabel
        {
            /// <summary>
            /// <para>@type dictionaryKey (moveCameraToLabel_id)</para>
            /// </summary>
            public const string id = "id";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string duration = "duration";
        }
        /// <summary>
        /// <para>@function shakeCamera</para>
        /// </summary>
        public static class shakeCamera
        {
            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string intensity = "intensity";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string duration = "duration";
        }
        /// <summary>
        /// <para>@function moveCharacterAt</para>
        /// </summary>
        public static class moveCharacterAt
        {
            /// <summary>
            /// <para>@type dictionaryKey (party)</para>
            /// </summary>
            public const string id = "id";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string x = "x";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string y = "y";

            /// <summary>
            /// <para>@type boolean</para>
            /// </summary>
            public const string absolut = "absolut";
        }
    }
}
